version: "3.8"

services:
  sap-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sap-fastapi-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
